RDKBDEV-2735 : Enable -Werror and -Wall in RdkVlanManager.
rdkcentral/meta-rdk-wan pull request #17
Opened 2024-07-02 12:07 UTC by sanjaynayakk

Reason for change:
Enabling -Werror and -Wall in RdkVlanManager.

Test Procedure: Performed RdkVlanManager Sanity test.
Risks: None.

2024-07-03 14:55 UTC, scthunderbolt requested changes
SRCREV also needs to be updated to fix all the warnings as errors.

2024-07-10 14:15 UTC, pradeeptakdas commented
Internal ticket created for testing https://ccp.sys.comcast.net/browse/RDKCOM-4905

2024-07-16 17:47 UTC, guto86 approved these changes

2024-08-20 16:20 UTC, guto86 approved these changes

2024-10-15 14:35 UTC, kul2241 approved these changes
good to go, tested

2024-10-15 14:44 UTC, kul2241 requested changes
we need to change GIT_TAG=RC1.2.0 which is latest tag of vlanmanager for meta-rdk-wan tag=RC1.5.0a

2024-10-16 13:36 UTC, kul2241 approved these changes

2024-10-17 09:52 UTC, kul2241 commented
> SRCREV also needs to be updated to fix all the warnings as errors.

i believe it would be solved after rebase of code. pls review again.

2024-10-17 10:59 UTC, scthunderbolt approved these changes

2024-10-18 11:03 UTC, merged