fix build issue and setup recipes to use git tag versions in packages
rdkcentral/meta-rdk-wan pull request #18
Opened 2024-07-03 10:53 UTC by berilevi

2024-07-03 10:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/rdkcentral/meta-rdk-wan?pullRequest=18) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/rdkcentral/meta-rdk-wan?pullRequest=18) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/rdkcentral/meta-rdk-wan?pullRequest=18) it.</sub>

2024-07-03 10:56 UTC, guto86 approved these changes

2024-07-03 12:28 UTC, guto86 approved these changes

2024-07-03 13:39 UTC, scthunderbolt requested changes

2024-07-03 13:39 UTC, scthunderbolt commented on recipes-ccsp/ccsp/rdk-wanmanager.bb
> +PV = "${SRCREV_WanManager}"
This is failing kirkstone builds:
"
ERROR: rdk-wanmanager-v2.2.0-r0 do_fetch: Bitbake Fetcher Error: FetchError("Recipe uses a floating tag/branch 'v2.2.0' for repo 'github.com/rdkcentral/RdkWanManager.git' without a fixed SRCREV yet doesn't call bb.fetch2.get_srcrev() (use SRCPV in PV for OE).", None)
"
PV has to have SRCPV in it for kirkstone.
Suggest you change it to 
PV = "${SRCREV_WanManager}+git${SRCPV}"
or something like that.

Same is true for the other recipes.

2024-07-04 12:09 UTC, scthunderbolt approved these changes
LGTM

2024-07-04 12:24 UTC, merged