RDKBDEV-2764 : Enable -Werror and -Wall in RdkPppManager.
rdkcentral/meta-rdk-wan pull request #21
Opened 2024-07-09 12:05 UTC by sanjaynayakk

Reason for change:
Enabling -Werror and -Wall in RdkPppManager.

Test Procedure: Sanity test.
Risks: None.

2024-07-10 14:37 UTC, pradeeptakdas commented
Internal ticket for tracking build and testing https://ccp.sys.comcast.net/browse/RDKCOM-4908

2024-08-20 15:47 UTC, guto86 submitted a review, later dismissed

2024-08-30 12:50 UTC, scthunderbolt requested changes

2024-08-30 12:50 UTC, scthunderbolt commented on recipes-ccsp/ccsp/rdk-ppp-manager.bb
> +    -Werror \
GIT_TAG = "RC1.1.0b" also needs to be updated to a version that fixes all the warnings.

2024-10-15 14:47 UTC, kul2241 requested changes
the changes need to be done on latest recipe file, which have version tag:v1.1.0 and meta-rdk-wan tag: RC1.5.0a

2024-10-16 13:36 UTC, kul2241 approved these changes

2024-10-17 10:59 UTC, scthunderbolt commented
Build is still failing.

2024-10-17 12:24 UTC, sanjaynayakk commented
Hi @scthunderbolt 

Change for those are fixed as per of commit https://github.com/rdkcentral/RdkPppManager/commit/0c5de5ddfe7fc28a99f81e94f59a11cb61c258dd

it's not included in release https://github.com/rdkcentral/RdkPppManager/releases

2024-10-21 06:13 UTC, sanjaynayakk commented
I check locally there are some werror added recent commit.. will check and update here.

2024-10-23 09:45 UTC, kul2241 requested changes
sky platform getting lots of format error, so we need to add -Wno-format  buil flag in cflag too.

2025-01-22 14:58 UTC, pradeeptakdas commented
Hi @kul2241 
Please merge this PR (https://github.com/rdkcentral/RdkPppManager/pull/27). Once this PR merged and release you can safely merge the meta layer changes.

2025-01-24 13:42 UTC, guto86 approved these changes

2025-01-24 14:01 UTC, kul2241 approved these changes

2025-01-28 18:02 UTC, merged